<?php

		$domain_name = "montellanoestructuras.com";

		$to = "clientes@montellano-eyc.com";

		$subject = "Contacto del formulario de la página web $domain_name";

		$message = "The following information was submitted to $domain_name.\n\n";

		foreach($_POST as $key => $value) {

			if (strlen($value) > 0) {

				$title = strtr(strtoupper($key),"_"," ");

				$message .= "$title: $value\n";

			}

		}

		$message .= "\nNote: this is an autogenerated email from $domain_name -- do not reply.\n";

		$headers = "From: $domain_name <automailer@$domain_name>\n";

		mail($to, $subject, $message, $headers);

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>

<head>

<title></title>

<meta http-equiv="content-type" content="text/html;charset=iso-8859-1">

<script type="text/javascript">window.onload=function() {self.location.replace("enviado.html");};</script>

</head>

<body></body></html>